server:
  port: ${PORT:8098}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/

info:
  app:
    name: bookstore-service

spring:
  application:
    name: bookstore-service

management:
  security:
    enabled: false